version: '3.3'

# Use root/example as user/password credentials
services:
  db:
    container_name: akd-test-db
    platform: linux/x86_64
    image: mysql
    command: --mysql-native-password=ON
    restart: unless-stopped
    ports:
      - "8001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: default
