[package]
name = "akd_local_auditor"
default-run = "akd_local_auditor"
version = "0.0.0"
authors = ["Sean Lawlor <seanlawlor@fb.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
bytes = "1"
winter-crypto = "0.2"
winter-math = "0.2"
tokio = { version = "1.10", features = ["full"] }
tokio-stream = "0.1"
colored = "2.0.0"
hex = "0.4.3"
rand = "0.8"
log = { version = "0.4.8", features = ["kv_unstable"] }
once_cell = "1"
thread-id = "3"
multi_log = "0.1"
clap = { version="3", features = ["derive"] }
qr2term = "0.3"

aws-config = "0.47.0"
aws-sdk-s3 = "0.17.0"

akd = { path = "../akd", features = ["public-tests", "public_auditing"] }
