name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Login to crates.io
      run: cargo login $CRATES_IO_TOKEN
      env:
        CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}
    - name: Dry run publish AKD
      run: cargo publish --dry-run --manifest-path Cargo.toml -p akd
    - name: Publish crate akd
      run: cargo publish --manifest-path Cargo.toml -p akd
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
    - name: Run the script that waits for AKD to be published
      run: bash ./.github/workflows/wait-for-akd-publish.sh
    - name: Dry run publish AKD_MYSQL
      run: cargo publish --dry-run --manifest-path Cargo.toml -p akd_mysql
    - name: Publish crate akd_mysql
      run: cargo publish --manifest-path Cargo.toml -p akd_mysql
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
    - name: Dry run publish AKD_CLIENT
      run: cargo publish --dry-run --manifest-path Cargo.toml -p akd_client
    - name: Publish crate akd_client
      run: cargo publish --manifest-path Cargo.toml -p akd_client
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
