name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}

    - uses: actions/checkout@main

    - name: Login to crates.io
      run: cargo login $CRATES_IO_TOKEN
      env:
        CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}

    - name: Dry run publish akd_core
      run: cargo publish --dry-run --manifest-path Cargo.toml -p akd_core

    - name: Publish crate akd_core
      run: cargo publish --manifest-path Cargo.toml -p akd_core
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}

    - name: Wait for necessary akd_core version to be available
      run: bash ./.github/workflows/wait-for-crate-dependency.sh akd akd_core

    - name: Dry run publish AKD
      run: cargo publish --dry-run --manifest-path Cargo.toml -p akd

    - name: Publish crate AKD
      run: cargo publish --manifest-path Cargo.toml -p akd
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
